import {
  BadgeCheck,
  Bell,
  Building2,
  CalendarClock,
  ClipboardCheck,
  Database,
  Gauge,
  FileStack,
  History,
  Inbox,
  LayoutDashboard,
  Layers,
  MonitorSmartphone,
  Network,
  Plug,
  PlugZap,
  RefreshCw,
  ScanSearch,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Ticket,
  UploadCloud,
  CloudUpload,
  Wrench,
  Users,
  FileBarChart,
  FileText,
  FileUp,
  FileScan,
  KeyRound,
  UserCog,
  Landmark,
  Percent,
  BookCopy
} from "lucide-react";

// Mỗi mục tương ứng 1 UC/nhóm UC đã có giao diện. Khi thêm UC mới có màn hình,
// bổ sung vào đây theo đúng nhóm nghiệp vụ (xem ARCHITECTURE.md mục 2).
export const NAV_SECTIONS = [
  {
    label: "Quản trị hệ thống",
    items: [
      { to: "/org-units", label: "Cơ cấu tổ chức", icon: Building2 },
      { to: "/users", label: "Người dùng", icon: Users },
      { to: "/permissions", label: "Quyền người dùng", icon: KeyRound },
      { to: "/roles", label: "Vai trò người dùng", icon: UserCog },
      { to: "/system-config", label: "Cấu hình hệ thống chung", icon: Settings },
      { to: "/integration-config", label: "Cấu hình tích hợp", icon: Network },
      { to: "/notification-channels", label: "Cấu hình kênh thông báo", icon: Bell },
      { to: "/audit-logs", label: "Nhật ký truy cập và thao tác", icon: FileText },
      { to: "/ai-audit-logs", label: "Quản trị AI Audit Log", icon: ScanSearch },
      { to: "/guide-documents", label: "Tài liệu hướng dẫn sử dụng", icon: FileStack },
      { to: "/sessions", label: "Quản lý phiên đăng nhập", icon: MonitorSmartphone },
    ],
  },
  {
    label: "Dữ liệu",
    items: [
      { to: "/data-sources", label: "Nguồn dữ liệu", icon: Database },
      { to: "/connectors", label: "Thư viện bộ kết nối", icon: Plug },
      { to: "/source-connections", label: "Cấu hình kết nối nguồn", icon: PlugZap },
      { to: "/datasets", label: "Định nghĩa tập dữ liệu của nguồn", icon: Layers },
      { to: "/scheduled-tasks", label: "Cấu hình tác vụ điều phối", icon: CalendarClock },
      { to: "/ingestion-runs", label: "Lịch đầy đủ dữ liệu + Lịch sử chạy", icon: History },
      { to: "/incremental-sync", label: "Đồng bộ tăng dần từ API/DB", icon: RefreshCw },
      { to: "/schema-registry-checks", label: "Kiểm tra Schema Registry", icon: ShieldAlert },
      { to: "/tabmis-intake", label: "Tiếp nhận file thủ công TABMIS", icon: UploadCloud },
      {
        to: "/intake-reconciliation",
        label: "Đối soát phiên intake",
        icon: ClipboardCheck,
      },
      {
        to: "/reconciliation-tickets",
        label: "Xử lý ticket đối soát với chủ quản nguồn",
        icon: Ticket,
      },
      { to: "/qlvbdh-intake", label: "Tiếp nhận văn bản QLVBĐH", icon: FileUp },
    ],
  },
  {
    label: "Chuẩn hóa và quản trị dữ liệu",
    items: [
      { to: "/parsing-jobs", label: "Phân tích dữ liệu có cấu trúc", icon: ShieldCheck },
      { to: "/mapping-jobs", label: "Ánh xạ trường sang dạng chuẩn", icon: ShieldCheck },
      { to: "/ocr-jobs", label: "Phân tích PDF/bản quét + OCR", icon: FileScan },
      { to: "/unmapped-queue", label: "Xử lý hàng đợi chưa ánh xạ", icon: Inbox },
      { to: "/org-unit-catalog", label: "Quản lý danh mục đơn vị", icon: Network },
      { to: "/budget-item-catalog", label: "Danh mục khoản mục NSNN", icon: Landmark },
      { to: "/asset-group-catalog", label: "Quản lý danh mục nhóm tài sản", icon: Percent },
      { to: "/catalog-entries", label: "Quản lý danh mục mặt hàng, loại văn bản, nguồn vốn", icon: BookCopy },
      { to: "/catalog-change-approvals", label: "Phê duyệt thay đổi danh mục nhạy cảm", icon: ClipboardCheck },
      { to: "/quality-rules", label: "Quản lý quy tắc kiểm tra chất lượng", icon: Gauge },
      { to: "/quality-checks", label: "Chạy kiểm tra chất lượng dữ liệu", icon: BadgeCheck },
      { to: "/quality-exceptions", label: "Xử lý ngoại lệ chất lượng", icon: ShieldAlert },
      { to: "/curated-publish", label: "Công bố vào kho chuẩn hoá + batch_summary", icon: CloudUpload },

    ],
  },
  {
    label: "Khai thác",
    items: [
      { to: "/dashboard", label: "Bảng điều khiển", icon: LayoutDashboard, disabled: true },
      { to: "/reports", label: "Báo cáo", icon: FileBarChart, disabled: true },
    ],
  },
  {
    label: "Nền tảng",
    items: [
      { to: "/integrations", label: "API & tích hợp", icon: Network, disabled: true },
      { to: "/ai", label: "Trợ lý AI", icon: Sparkles, disabled: true },
      { to: "/ops", label: "Vận hành", icon: Wrench, disabled: true },
    ],
  },
];